language: android
jdk: oraclejdk8

sudo: false

android:
  components:
    - tools
  licenses:
    - android-sdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_cbeaef396b1f_key -iv $encrypted_cbeaef396b1f_iv -in archive.tar.gz.enc -out archive.tar.gz -d
  - tar -xzvf archive.tar.gz
  - chmod +x gradlew

before_script:
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platform-tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;30.0.1"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platforms;android-25"

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

deploy:
  provider: releases
  api_key:
    secure: goOFc+9jCVBHgu2PJRkpM8Mp8BtuYmk+BXw4Bkoz7Uz3cnLXShKal25V1k5qrW+weITsMkNDDS7atHyagCNhhlozgSpIOUHHJ4dM28w0fWhbBz4rImrw4QOavGGKrAKqoqCqmwHvScw7ThImPy1MP/WHnZxI5pkvyy2APYaYrEwfeWJz0BC4Hbne+dE3WUnNk3NTPK1NhM9ubfCyuvv4hDl3BDlv3JDuTTDKpiDeeNYXUpcKYLoazFqNLIB7EBRVrd4Cb58A6w+KwnLRJkv7W0FcG3Tzyi8+wR7nhK3IUrDM93i2DSH/LzV5KE06mf+KI1umlljyxOYypdN42ehC7JzP1UpA5IVNxUIG4RpUnujyQMqCGopqm8Im0ANwMiLJvLegFoL1h8l5Fq5LfNAbCTgP+9o2iBTC95WtrwUtTOUxkUS/tQu7iGkkacUkJ6oKq/eVBoAPNfQcZ7dWArSxLrYhvNRsbn8wre2GIa0j/5MB3hTIPrD7yetvsy9bVDkbW5qfSjGX+DLd7dLPocA2ZzWv7C7qscPpx92WLaF5TU1VmhLOkohXntEU50fegB1yWcUgdnyqhkGlVtbQ+yBu0Ohopv04//Kms11xp9Q15ZEdNGN7VAsF5aFU2eE0cbhj0J3oWh//fx8ElkTor6jN3IcDgyALjmh+yrgxyHthz5E=
  file: app/release/app-release.apk
  skip_cleanup: true
  on:
    repo: eby8zevin/TravisCI-Android
    tags: true

notifications:
  email: false