language: android
jdk: oraclejdk8

android:
  components:
    - tools
  licenses:
    - android-sdk-license-.+

before_install:
  - chmod +x gradlew

before_script:
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platform-tools"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;30.0.1"
  - echo yes | ${ANDROID_HOME}tools/bin/sdkmanager "platforms;android-25"

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

deploy:
  provider: releases
  api_key:
    secure: ZgEKNC+9lagGldQ822miQhGTVp1navz0jup9NZlQzecwJ7tLzH8Qi32A5TwYvCJkLJyGz+uxhXfqveqf0cRnQ1NhsWPp2Ocu9gDCJZ15cUaMEMTj85CG/QoKXylPP1qlWRibCEXt7ZwiKYnNaoiy2ZV/vIRjhxIn3DueQwyCBSNsRud9jKYTRotIun6ks2uBALtNmtuoEMjs+796BLLZBu+Kn8wPGst7W0zdqlVlIbWeyrPhWRueKa6ECDikPJUNquIScZwBjZJXolgvum01PblRY6VaIvpKnR0A8p6W88uRfG4MLjnZu9DQLk270tr44mVo6kVKQ+iiFwALNn7aifhn/wfFVf2jMWu/k970RpiduKNPCVTZOzW70OGSpUDGN67jqXUcg60D+qmj6FbwVn8sJY1YxfZcesoNEorUC2l2roqHUPaT3GW6kuUB5hUAUCfJkCMj9anUH6LERVYaYv7ggOKTxb050XN2af5xI/Q30Y8dF95zCb7pHaZvZvMZssDirI5mTQrYHARZiW3ALP28EfGtv4X7ajKC0T0XbrBcObY7quTuDAa1OTGfLiGl1CNS9VS+oF3fHZY6ytNVGGgezxQIV/zcscY+hFlcY9IoKXW5UOOTtIZn4nvUkk7ywPtOzunysFiQ8d7Yp4zhGZBFR0axm7UTQkqoieRdXVw=
  file: app/release/app-release.apk
  skip_cleanup: true
  on:
    repo: eby8zevin/TravisCI-Android
    tags: true

notifications:
  email: false