language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-30.0.1
    - android-30
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api_key:
    secure: ${{ secrets.TRAVIS_CI }}
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: eby8zevin/TravisCI-Android
    tags: true

notifications:
  email: false
